### ISSUE TITLE
Combobox isn't reset during Form reset.

### ISSUE THREAD

**Issue by ryanschneider** [alexkuz/react-input-enhancements#1]
Say I have a component rendering a Combobox inside a form like so:

```
<form>
  <Combobox defaultValue=""
                       options={this.state.options}
                       autosize>
        {inputProps =>
            <input {...inputProps}
                       type='text'
                       placeholder='No Selection'
                       />
        }
    </Combobox>
    <ButtonInput type="reset"
                          value="Reset Cards"
                          onClick={this.handleReset.bind(this)}
     />
</form>
```

If the form is reset I can't figure out how to reset the internal state of the Combobox, so as soon as it gets focus again the old value is displayed in the `<input/>`.  I believe I basically want to call `Autocomplete.setValue("")` but don't see a ref chain I can use to do so.

Any ideas?  I'd be happy to send a PR if you can give me some guidance.  One idea I had was to add refs to the contained Dropdown and Autocomplete in the various `Combobox.render*()` routines, but I'm not sure if that's the best approach.

Also, BTW, very happy with the module so far, great work!

**Comment by alexkuz** [comment]
Yeah, It's not working properly in a controlled mode for now (when `value` prop is set explicitly), but I think it should be controlled via `value` prop, not the `setValue` method.

Here, I've made some changes, now it should work better (see demo - haven't published it yet, should try it in "real live" code first).

**Comment by ryanschneider** [comment]
Awesome, thanks, I'll check it out when I get a chance.

**Comment by ryanschneider** [comment]
I had a brief chance to try it out, seems to be working better but I'm still seeing the old value when the input gains focus.  I'd tried adding a `ref` to the Combobox:

```
<form>
  <Combobox options={this.state.options}
                      ref="combo"
                      autosize>
      {inputProps =>
            <input {...inputProps}
                       type='text'
                       placeholder='No Selection'
                       />
        }
    </Combobox>
    <ButtonInput type="reset"
                          value="Reset Cards"
                          onClick={this.handleReset.bind(this)}
     />
</form>
```

And then calling `this.refs.combo.setState({value: null})` in my handleReset function, but that didn't help either.  I need to dig a bit more to understand what you're doing in the demo.  This is a sideproject I'm working on, so only can look at it in fits and starts.

I'm not sure why you brought up controlled though, in my example the only controlled item was the reset button, the combobox is uncontrolled (or at least that's my intent).

**Comment by ryanschneider** [comment]
I was able to progress on this some more, and realized that to reset the value, I actually needed to make my combobox controlled like you did in the demo, so its working now.
