### ISSUE TITLE
Chars come out of order

### ISSUE THREAD

**Issue by vicentedealencar** [alexkuz/react-input-enhancements#13]
Hi,

my machine has been really slow recently, so when typing really fast on a <Mask/> input sometimes it goes out of order. I was using this pattern '000000000-00' and for example typing '12345678901' would end up in something like '123465798-10'

As I am already using a "forked" version because of #10, I went there and removed the setTimeout on the [hack](https://github.com/alexkuz/react-input-enhancements/blob/eeddfd74116ec3139a02bec42e609f6b296aa635/src/Mask.jsx#L84)

It seems to work without side effects. Is it really necessary?

**Comment by alexkuz** [comment]
Seems like it doesn't change anything now, indeed. Let's remove this.

**Comment by alexkuz** [comment]
Published in v0.4.9
