### ISSUE TITLE
ReferenceError: window is not defined when using server-side rendering

### ISSUE THREAD

**Issue by mloncaric** [alexkuz/react-input-enhancements#14]
https://github.com/alexkuz/react-input-enhancements/blob/eeddfd74116ec3139a02bec42e609f6b296aa635/src/utils/getComputedStyle.js#L3

The following check should be enough i think
`typeof window != "undefined"`

Smth like:
`typeof window != "undefined" && !('getComputedStyle' in window) && (window.getComputedStyle = (function (window) {`
instead of
`!('getComputedStyle' in window) && (window.getComputedStyle = (function (window) {`

**Comment by alexkuz** [comment]
Thank you! I would appreciate if you send a PR, btw :)

**Comment by alexkuz** [comment]
Should work now in `v0.5.1`
