### ISSUE TITLE
in proper css className

### ISSUE THREAD

**Issue by atZhengda** [alexkuz/react-input-enhancements#15]
found the rendered element are of undesired css class name, eg '.inputPopup--jss-0-0' and '.caret--jss-0-1' (note the dot inside the name). Hence the input fields are not properly rendered.

env: webpack: 1.12.15, babel: 6.5.2, browser: chrome 49.0, os: osX 10.11.2

Can you please look into this? Thank you very much!

**Comment by atZhengda** [comment]
resolved by clean install of everything. Might be caused by some legacy version of react components.

Thanks

**Comment by alexkuz** [comment]
Thank you for update! Probably that was a bug in `jss`.
