### ISSUE TITLE
'disabled' doesn't work (and is wrong in demo) in Combobox

### ISSUE THREAD

**Issue by kaiserkoenig** [alexkuz/react-input-enhancements#16]
Hi,

when i set some options to disabled, i still can select them, which is not the expected behavior.
(And, in your demo, you wrote 'disable', but only 'disabled' works. )

Thx

Timo

**Comment by alexkuz** [comment]
Whoopsie! Thanks for the report, will fix that later. Unless you want to make a PR :)

**Comment by kaiserkoenig** [comment]
:) sorry, but there's a lot of other stuff to do these days

**Comment by alexkuz** [comment]
Should work fine in current versions (not sure since what exactly, but at least `>v0.5.0`)
