### ISSUE TITLE
Changing the Color of the selected Item in Autocomplete+Combobox

### ISSUE THREAD

**Issue by ekarni** [alexkuz/react-input-enhancements#18]
I created an Autocomplete + Combobox that works perfectly, but I'm having some issues with styling.  After you select an item, it is highlighted which is fine but I want to choose the color of the highlight.

**Comment by alexkuz** [comment]
It is now configurable via `theme` prop (see `inputEnhancementsOption` in [createStyling.js](https://github.com/alexkuz/react-input-enhancements/blob/master/src/createStyling.js))
