### ISSUE TITLE
Decouple styling and logic

### ISSUE THREAD

**Issue by kujon** [alexkuz/react-input-enhancements#23]
It would be absolutely awesome if this library was exposed as logic + markup and the styles came as a separate package. If one isn't doing jss in their project, the bundle size suffers and one ends up resorting to selector wars.

**Comment by alexkuz** [comment]
Good point!

This would require some patch in `react-date-picker`, though, as there is no direct way to setup styles, as far as I know (or find another module - but apart from custom styling `react-date-picker` works quite nicely).

**Comment by kujon** [comment]
Awesome stuff! Raised it with them as well ^^ https://github.com/zippyui/react-date-picker/issues/99

**Comment by gertsonderby** [comment]
I'd like this too. This lib is basically exactly what I need right now but I need to style it, and I don't use JSS.

**Comment by alexkuz** [comment]
Yes, there will be update soon (I hope) - it will be using modified version of `react-day-picker` (instead of `react-date-picker`) with themes support (see [react-base16-styling](https://github.com/alexkuz/react-base16-styling)), so it will be agnostic to your styling preferences.

**Comment by alexkuz** [comment]
@kujon in `v0.5.0-beta1` (in `next` branch) `react-date-picker` is replaced with `react-day-picker-themeable` (my version of `react-day-picker` by @gpbl), which is maybe not so advanced, but was easier to inject themes in it. `JSS` dependency is removed now.
