### ISSUE TITLE
timestamp input for DatePicker

### ISSUE THREAD

**Issue by vim-zz** [alexkuz/react-input-enhancements#26]
hi!, great components and documentation. i need to be able to allow my users to also use timestamps (milisec since epoch) as valid date on the date picker - is there a way to override the mask, so it accept long integers? just to be clear it doesn't need to be rendered on the popup.

**Comment by alexkuz** [comment]
![](http://i.gr-assets.com/images/S/compressed.photo.goodreads.com/hostedimages/1451272452i/17523787.jpg)

Now you can! You can patch it with `onValuePreUpdate` (I've included examples in README and demo)
