### ISSUE TITLE
Full width dropdown popup

### ISSUE THREAD

**Issue by pmendelski** [alexkuz/react-input-enhancements#28]
Hi, is there an easy way to make dropdown popup full width?

To be exact I would like to add rule `width: 100%` to `popup--jss-0-5` class but I know it's a bad idea to add css rules to a generated class name.

**Comment by pmendelski** [comment]
I hacked it with: 

``` js
const onRenderList = (className, style = {}, ...args) =>
  Dropdown.defaultProps.onRenderList(className, { ...style, width: '100%' }, ...args);
```

...but it is far from perfection ;)

**Comment by alexkuz** [comment]
@mendlik `Dropdown` is now configurable via `theme` prop, it goes like this:

``` js
{
  inputEnhancementsPopup: ({ style }) => ({
    style: {
      ...style,
      width: '100%'
    }
  })
}
```

Sorry my answer took so long :)

**Comment by pmendelski** [comment]
Thanks

**Comment by Ivan-Feofanov** [comment]
Can you pass the example for Combobox?
ok, i find how:

```
<Combobox
  theme={{
    inputEnhancementsPopup: ({ style }) => ({
      style: {
        ...style,
        width: '100%'
      }
    })
  }}
/>
```
