### ISSUE TITLE
react modules are in the devDependencies

### ISSUE THREAD

**Issue by nadav-dav** [alexkuz/react-input-enhancements#3]
Modules like `react-bootstrap`, `react-pure-renderer` should be in `dependencies` and not `devDependenices`, since it used in production and is being bundled with the component when building the project with webpack.

what do you think? am i missing anything?

**Comment by alexkuz** [comment]
`react-pure-renderer` should, indeed, but not `react-bootstrap` - it's used only in demo.

**Comment by nadav-dav** [comment]
created a pull request :) https://github.com/alexkuz/react-input-enhancements/pull/4

**Comment by alexkuz** [comment]
Thank you!
