### ISSUE TITLE
Question: control the size of DatePicker

### ISSUE THREAD

**Issue by alexbeletsky** [alexkuz/react-input-enhancements#30]
I have a form where `DatePicker` is integrated,

``` js
  <form id="timeline" className="form" onChange={onChange} onSubmit={validateTimelineForm(form, onSubmit, onErrors)}>
    <div className="row">
      <DatePicker className="col-xs-6" onRenderCaret={noop}>
        {inputProps =>
          <div className={cx('form-group', { 'has-danger': form.errors.applicationStart })}>
            <label htmlFor="applicationStart">
              Start of Application:
            </label>
            <input
              { ...inputProps }
              type="text"
              className={cx(inputProps.className, 'form-control')}
            />
          </div>
        }
      </DatePicker>

      // ...
```

`DatePicker` popup appears after click, but it's ridiculously big,

<img width="692" alt="screenshot 2016-07-25 17 10 57" src="https://cloud.githubusercontent.com/assets/304929/17107465/a2704128-528f-11e6-8ce7-0b381d4d7d0c.png">

Is there a way to control it's dimensions?

**Comment by alexkuz** [comment]
@alexbeletsky `DatePicker` is now fully configurable via `theme` props, though it would be nice to know if it's working fine now with default styles.
