### ISSUE TITLE
unknown props warning on React v15.2.0

### ISSUE THREAD

**Issue by kennyhk** [alexkuz/react-input-enhancements#31]
please see
https://facebook.github.io/react/warnings/unknown-prop.html

<img width="760" alt="screen shot 2016-07-26 at 12 30 33 pm" src="https://cloud.githubusercontent.com/assets/10775572/17126132/e49897e2-532c-11e6-860e-b0d31defe533.png">

**Comment by kennyhk** [comment]
hello, any update please?

**Comment by jxom** [comment]
+1

**Comment by alexkuz** [comment]
@kennyhk this will be gone in `v0.5.0` (see https://github.com/alexkuz/react-input-enhancements/tree/v0.5.0-beta1)

**Comment by alexkuz** [comment]
@JMoxey please use github reactions instead of "+1" 🙂

**Comment by kennyhk** [comment]
@alexkuz thank you very much!!!!
