### ISSUE TITLE
AutoComplete on Combobox is buggy on IE/Edge

### ISSUE THREAD

**Issue by kennyhk** [alexkuz/react-input-enhancements#33]
i am using the babel-polyfill let Combobox working on  IE 11 and Edge, but when enable autocomplete, the input text will be reversed. For example, when input "Hello",  the combobox display as "olleH".

my codes (please note that also enable auto-size: 

```
let props = {
            options: suggestions,
            onChange: this.onKeywordChange.bind(this),
            onValueChange: this.onValueChange.bind(this),
            autocomplete: true, // buggy on IE11
            autosize: true
        };
return <Combobox {...props}>
            <FormControl type='search' placeholder={placeholder} value={this.state.suggestion.keyword} ref="keyword"/>
        </Combobox>;
```

**Comment by alexkuz** [comment]
@kennyhk please check if it working in latest version ([v0.5.1](https://github.com/alexkuz/react-input-enhancements/tree/v0.5.1))

**Comment by kennyhk** [comment]
follow up:  i just update as latest verion today (v0.5.3), bug this bug is still exists

**Comment by kennyhk** [comment]
follow up: 
this bug is fixed via "registerInput",  thank you!
