### ISSUE TITLE
DatePicker input pattern validation

### ISSUE THREAD

**Issue by alexbeletsky** [alexkuz/react-input-enhancements#35]
I have `<DatePicker />` without `value` and `defaultValue`, only listening to `onChange` and updates redux storage.

Once I selected the date and try to submit my form, I see error pops-up by Chrome,

<img width="700" alt="screenshot 2016-07-26 10 46 27" src="https://cloud.githubusercontent.com/assets/304929/17131555/4d337c4a-531e-11e6-8cf4-1753115a2716.png">

The pattern I see,

<img width="763" alt="screenshot 2016-07-26 10 46 48" src="https://cloud.githubusercontent.com/assets/304929/17131569/56f857c8-531e-11e6-98a6-e514a7cfe336.png">

It looks strange, because `\d\d\d` would not match `Wed` and also, not sure about `00/00/000` would it work at all?

Will providing `pattern` prop allow to workaround the problem?

**Comment by alexbeletsky** [comment]
The problem is likely here,

https://github.com/alexkuz/react-input-enhancements/blob/master/src/DatePicker.jsx#L28

Why `props.pattern.replace(/ddd/g, '\\d\\d\\d').replace(/[DMY]/g, '0')`?

**Comment by alexbeletsky** [comment]
Just quickly tried it in Chrome, this pattern seems to work,

`\w{3,} \d\d/\d\d\/\d\d\d\d`

But honestly, I would just throw the default value away, since very likely you perform validation of fields anyway. If user wants to have HTML pattern attribute, she can submit it via props. What do you think? @alexkuz

**Comment by alexkuz** [comment]
Yes, the error here is that `<input />` receives this pattern, which it shouldn't - it's a pattern for `<Mask />` (and it's not a regex, obviously).

**Comment by alexbeletsky** [comment]
I'm looking to the code right now.. I don't want to modify before I can run in in demo app, currently having such a problem with the build.

<img width="792" alt="screenshot 2016-07-26 11 22 51" src="https://cloud.githubusercontent.com/assets/304929/17132769/7500cc32-5323-11e6-8c5c-12f67ea20ae5.png">

Any hints?

**Comment by alexbeletsky** [comment]
As for issue, I would avoid using `{ ...props }` here,

https://github.com/blogfoster/react-input-enhancements/blob/master/src/DatePicker.jsx#L78

and do explicit props for `<InputPopup />`, and put only required properties.. What do you think?

**Comment by alexbeletsky** [comment]
PR https://github.com/alexkuz/react-input-enhancements/pull/36
