### ISSUE TITLE
Missing - changelog

### ISSUE THREAD

**Issue by petrleocompel** [alexkuz/react-input-enhancements#37]
Its verry hard to watch which changes will break project. 

It would be very cool to have changelog. And on each version just write down what has changed and if there is any breaking change.

For example [Bootstrap changelog](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md)

Or at versions as comment

**Comment by ReadyPlayerNaN** [comment]
Or at least please make a tag for each release.

**Comment by alexkuz** [comment]
@just-paja oh, I forgot tags aren't pushed to remote rep by default :) Fixed that.

**Comment by ReadyPlayerNaN** [comment]
@alexkuz lol :) 

Now you can generate changelog from commit history.

**Comment by alexkuz** [comment]
Now it's in `next` branch, soon will be in master
