### ISSUE TITLE
IE10, IE11 ComboBox popup completely overflows

### ISSUE THREAD

**Issue by ReadyPlayerNaN** [alexkuz/react-input-enhancements#39]
ComboBox has trouble in IE 11 because of [flexbox bug](https://connect.microsoft.com/IE/feedback/details/802625). The `max-height` style gets completely ignored, content of the ComboBox gets stretched and overflow gets ignored. I found only two simple solutions:
1.  [Set the height to specific size](http://stackoverflow.com/a/31816795) 
2. Don't use flexbox

**Comment by alexkuz** [comment]
Fixed in `v0.5.0`
