### ISSUE TITLE
Should the non-function children be deprecated?

### ISSUE THREAD

**Issue by alexkuz** [alexkuz/react-input-enhancements#41]
> All components accept function as a child, providing props as a first argument, which you should pass to your input component. If there is nothing else except input, it could be passed as a child directly (for simplicity).

I think the latter option should be deprecated. For example:

``` jsx
      <Autosize
        value={value}
        onChange={e => onChange(e.target.value)}
      >
        <FormControl
          type='text'
          value={value}
        />
      </Autosize>
```

It's not obvious that `Autosize` passes `onChange` prop to `FormControl` (moreover, if you pass `onChange` to `FormControl` here, it just won't work, as it will be overridden by `AutoSize`). In contrast, there is no such magic when you use a function, it's up to you how you use its arguments.

What do you think?

@alexbeletsky

**Comment by alexbeletsky** [comment]
That's an interesting question. From one hand, all my code is currently using functional components, but something like this:

``` jsx
<Autosize
  value={value}
  onChange={e => onChange(e.target.value)}
>
  {(props) => {
     // ...
   }};
</Autosize>
```

looks a bit ugly to me. So, what I typically do is something like,

``` jsx
const input = (props) => (<input> ... </input>);

<Autosize
  value={value}
  onChange={e => onChange(e.target.value)}
>
  {input}
</Autosize>
```

The syntax as from your example above looks much better to me. Of cause, it has another flow, of implicit parameters passing down to a child component.

I would leave the space for both options, depending on style preferred.

**Comment by alexkuz** [comment]
There is another reason I'd like to deprecate that - I want to get rid of implicit resolving `<input>` DOM node inside enhancement components. It means user should provide input ref manually. It's easy to do with `function` child:

``` jsx
<Autosize>
  {(inputProps, otherProps, registerInput) =>
    <input ref={c => registerInput(c)} />
  }
</Autosize>
```

However, if it is not a function, the only way I see (apart from resolving it implicitly) is to store `<input>` ref in component and pass it as a prop to component:

``` jsx
<Autosize input={this.input}>
    <input ref={c => this.input = c)} />
</Autosize>
```

...actually, it doesn't look so bad as I thought :)

**Comment by alexkuz** [comment]
Ok, now all components support this, the only change - `getInputComponent` callback instead of `input` prop (not really a change here, it was already done that way):

``` jsx
<Autosize getInputComponent={() => this.input}>
    <input ref={c => this.input = c)} />
</Autosize>
```
