### ISSUE TITLE
DateTime?

### ISSUE THREAD

**Issue by oyeanuj** [alexkuz/react-input-enhancements#5]
Hi @alexkuz! Thanks for the library, it looks great. I would love to use it but I also need to have a DateTime Picker instead of just a DatePicker. 

How would you suggest that I could do it while using this library?

**Comment by alexkuz** [comment]
You should use `onRenderCalendar`, that will return your datetime control instead of `react-date-picker`:

https://github.com/alexkuz/react-input-enhancements/blob/master/src/DatePicker.jsx#L44

https://react.rocks/example/input-moment - this one looks fine.

(although, there might be some problems with input masking, if you need to show time inside input - I haven't try that)

**Comment by oyeanuj** [comment]
@alexkuz thanks for the quick response! 

Masking was going to be my next response, any pointers there on how to incorporate that myself? Or would that be an enhancement for you to consider?

(FWIW, I am looking at https://github.com/dubert/react-kronos library at the moment as an example of a standard timepicker)

**Comment by alexkuz** [comment]
At least is should be changed here:

https://github.com/alexkuz/react-input-enhancements/blob/master/src/DatePicker.jsx#L28

(the laziest solution would be `.replace(/[DMYhms]/g, '0')`)

than a pattern with time format should work, like `'ddd DD/MM/YYYY, hh:mm'`

On the other side, if you're ok with separated date and time controls and you need only limited set of time values (like in `react-kronos` demo), you can just use two inputs - DatePicker and Dropdown with options like `['12:00 am', '12:30 am', ...]`, that you can parse then with `moment` and combine with DatePicker value.

**Comment by oyeanuj** [comment]
Ended up using this library (https://github.com/alanclarke/time-input) for time input, as it had some additional keyboard controls. My backup was editing `DatePicker` like you suggested as I think it would be a useful complement to the date picker that you already have. Thanks for your suggestions!
