### ISSUE TITLE
Uncaught Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by ekarni** [alexkuz/react-input-enhancements#7]
I attempted to integrate the autocomplete feature, but have run into this error whenever I attempt to access the website.

"Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `exports`."

Thanks

**Comment by alexkuz** [comment]
@ekarni I'll close it for now - please let me know if you think there is still an issue.
