### ISSUE TITLE
IE11 compatibility

### ISSUE THREAD

**Issue by ahskaus** [alexkuz/react-input-enhancements#9]
I tried this url http://alexkuz.github.io/react-input-enhancements/ in IE11, but get nothing. Works fine in Chrome and Firefox. I was wondering if the library doesn't support IE.

**Comment by alexkuz** [comment]
Not yet, apparently :)

Just checked MS Edge - it's quite buggy, but at least the page is working; haven't check earlier versions yet. I'll try to take a closer look some time later, thank you for bringing this up.

**Comment by alexkuz** [comment]
Should work now in `v0.5.0`
